language: php
php:
  - '7.1'
install:
  - composer install -a
before_script:
  - wget https://github.com/infection/infection/releases/download/0.8.1/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.8.1/infection.phar.pubkey
  - chmod +x infection.phar
script:
  - ./infection.phar --min-msi=100 --threads=4
